// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/m_spc_bk.tga
gfx/env/m_spc_dn.tga
gfx/env/m_spc_ft.tga
gfx/env/m_spc_lf.tga
gfx/env/m_spc_rt.tga
gfx/env/m_spc_up.tga
models/gunmanchronicles/beak.mdl
models/gunmanchronicles/bigmantaship.mdl
models/gunmanchronicles/epsilonmoon.mdl
models/gunmanchronicles/mantaship.mdl
models/gunmanchronicles/mayanplanet.mdl
models/gunmanchronicles/mayanring.mdl
models/gunmanchronicles/rheptor.mdl
models/gunmanchronicles/rustplanet.mdl
models/gunmanchronicles/scientist.mdl
models/gunmanchronicles/sitbandit.mdl
models/gunmanchronicles/sitgeneral.mdl
models/gunmanchronicles/v_hands.mdl
rewolf.wad
sound/gunmanchronicles/bandit/bandit_badfeeling.wav
sound/gunmanchronicles/bandit/breaking_orbit.wav
sound/gunmanchronicles/beak/pain2.wav
sound/gunmanchronicles/cinima/cini00_left.wav
sound/gunmanchronicles/cinima/cini00_right.wav
sound/gunmanchronicles/cinima/cini01_left.wav
sound/gunmanchronicles/cinima/cini01_right.wav
sound/gunmanchronicles/cinima/cini02_left.wav
sound/gunmanchronicles/cinima/cini02_right.wav
sound/gunmanchronicles/cinima/cini03_left.wav
sound/gunmanchronicles/cinima/cini03_right.wav
sound/gunmanchronicles/cinima/cini04_left.wav
sound/gunmanchronicles/cinima/cini04_right.wav
sound/gunmanchronicles/cinima/cini05_left.wav
sound/gunmanchronicles/cinima/cini05_right.wav
sound/gunmanchronicles/cinima/cini06_left.wav
sound/gunmanchronicles/cinima/cini06_right.wav
sound/gunmanchronicles/cinima/wormhole_entry.wav
sound/gunmanchronicles/general/general5_gs.wav
sound/gunmanchronicles/gscientist/beard10_gs.wav
update.wad
