// Created with resguy v4
// https://github.com/wootguy/resguy

models/gunmanchronicles/p_crowbar.mdl
models/gunmanchronicles/v_gcknife.mdl
models/gunmanchronicles/w_knife.mdl
models/gunmanchronicles/v_beam.mdl
models/gunmanchronicles/v_guasspistol.mdl
models/player/gunman/gunman.mdl
gfx/env/m_bas_bk.tga
gfx/env/m_bas_dn.tga
gfx/env/m_bas_ft.tga
gfx/env/m_bas_lf.tga
gfx/env/m_bas_rt.tga
gfx/env/m_bas_up.tga
gmdemo.wad
models/gunmanchronicles/Asteroid.mdl
models/gunmanchronicles/batterybot.mdl
models/gunmanchronicles/battgib.mdl
models/gunmanchronicles/guassammo.mdl
models/gunmanchronicles/gunmantrooper_ng.mdl
models/gunmanchronicles/holopipes.mdl
models/gunmanchronicles/null.mdl
models/gunmanchronicles/rockspin.mdl
models/gunmanchronicles/screen.mdl
models/gunmanchronicles/w_gauss.mdl
models/gunmanchronicles/w_shotgun.mdl
models/gunmanchronicles/tank.mdl
sound/buttons/spark5.wav
sound/buttons/spark6.wav
sound/gunmanchronicles/ambience/access_granted.wav
sound/gunmanchronicles/ambience/forcefield1.wav
sound/gunmanchronicles/ambience/forcefield2.wav
sound/gunmanchronicles/ambience/forcefieldshutdown1.wav
sound/gunmanchronicles/ambience/light_switch2.wav
sound/gunmanchronicles/ambience/panelmoves.wav
sound/gunmanchronicles/drone/drone_flinch1.wav
sound/gunmanchronicles/drone/drone_flinch2.wav
sound/gunmanchronicles/drone/drone_idle.wav
sound/gunmanchronicles/gunman/armor1.wav
sound/gunmanchronicles/gunman/armor2.wav
sound/gunmanchronicles/gunman/armor3.wav
sound/gunmanchronicles/gunman/armor4.wav
sound/gunmanchronicles/gunman/armor5.wav
sound/gunmanchronicles/gunman/briefing2.wav
sound/gunmanchronicles/gunman/explosives1.wav
sound/gunmanchronicles/gunman/explosives2.wav
sound/gunmanchronicles/gunman/explosives3.wav
sound/gunmanchronicles/gunman/gunman1.wav
sound/gunmanchronicles/gunman/gunman10.wav
sound/gunmanchronicles/gunman/gunman11.wav
sound/gunmanchronicles/gunman/gunman12.wav
sound/gunmanchronicles/gunman/gunman13.wav
sound/gunmanchronicles/gunman/gunman14.wav
sound/gunmanchronicles/gunman/gunman15.wav
sound/gunmanchronicles/gunman/gunman16.wav
sound/gunmanchronicles/gunman/gunman17.wav
sound/gunmanchronicles/gunman/gunman2.wav
sound/gunmanchronicles/gunman/gunman3.wav
sound/gunmanchronicles/gunman/gunman4.wav
sound/gunmanchronicles/gunman/gunman5.wav
sound/gunmanchronicles/gunman/gunman6.wav
sound/gunmanchronicles/gunman/gunman7.wav
sound/gunmanchronicles/gunman/gunman8.wav
sound/gunmanchronicles/gunman/gunman9.wav
sound/gunmanchronicles/gunman/hey.wav
sound/gunmanchronicles/gunman/mission1.wav
sound/gunmanchronicles/gunman/mission2.wav
sound/gunmanchronicles/gunman/mission3.wav
sound/gunmanchronicles/gunman/mission4.wav
sound/gunmanchronicles/gunman/mission5.wav
sound/gunmanchronicles/gunman/movement1.wav
sound/gunmanchronicles/gunman/movement2.wav
sound/gunmanchronicles/gunman/praise1.wav
sound/gunmanchronicles/gunman/praise2.wav
sound/gunmanchronicles/gunman/repair_guy1.wav
sound/gunmanchronicles/gunman/repair_guy2.wav
sound/gunmanchronicles/gunman/rocket1.wav
sound/gunmanchronicles/gunman/rocket10.wav
sound/gunmanchronicles/gunman/rocket2.wav
sound/gunmanchronicles/gunman/rocket3.wav
sound/gunmanchronicles/gunman/rocket4.wav
sound/gunmanchronicles/gunman/rocket5.wav
sound/gunmanchronicles/gunman/rocket6.wav
sound/gunmanchronicles/gunman/rocket7.wav
sound/gunmanchronicles/gunman/rocket8.wav
sound/gunmanchronicles/gunman/rocket9.wav
sound/gunmanchronicles/gunman/statue_room_guys1.wav
sound/gunmanchronicles/gunman/statue_room_guys2.wav
sound/gunmanchronicles/gunman/statue_room_guys3.wav
sound/gunmanchronicles/gunman/statue_room_guys4.wav
sound/gunmanchronicles/gunman/tank1.wav
sound/gunmanchronicles/gunman/tank2.wav
sound/gunmanchronicles/gunman/tank3.wav
sound/gunmanchronicles/gunman/tank4.wav
sound/gunmanchronicles/gunman/tank5.wav
sound/gunmanchronicles/gunman/tank6.wav
sound/gunmanchronicles/gunman/tank7.wav
sound/gunmanchronicles/gunman/tank8.wav
sound/gunmanchronicles/gunman/tank9.wav
sound/gunmanchronicles/gunman/urge_on1.wav
sound/gunmanchronicles/gunman/urge_on2.wav
sound/gunmanchronicles/gunman/urge_on3.wav
sound/gunmanchronicles/gunman/urge_on4.wav
sound/gunmanchronicles/range/failure_sound.wav
sound/gunmanchronicles/range/range1.wav
sound/gunmanchronicles/range/range10.wav
sound/gunmanchronicles/range/range11.wav
sound/gunmanchronicles/range/range12.wav
sound/gunmanchronicles/range/range13.wav
sound/gunmanchronicles/range/range14.wav
sound/gunmanchronicles/range/range15.wav
sound/gunmanchronicles/range/range16.wav
sound/gunmanchronicles/range/range17.wav
sound/gunmanchronicles/range/range18.wav
sound/gunmanchronicles/range/range19.wav
sound/gunmanchronicles/range/range2.wav
sound/gunmanchronicles/range/range20.wav
sound/gunmanchronicles/range/range21.wav
sound/gunmanchronicles/range/range22.wav
sound/gunmanchronicles/range/range23.wav
sound/gunmanchronicles/range/range24.wav
sound/gunmanchronicles/range/range25.wav
sound/gunmanchronicles/range/range3.wav
sound/gunmanchronicles/range/range4.wav
sound/gunmanchronicles/range/range5.wav
sound/gunmanchronicles/range/range6.wav
sound/gunmanchronicles/range/range7.wav
sound/gunmanchronicles/range/range8.wav
sound/gunmanchronicles/range/range9.wav
sound/gunmanchronicles/range/success_sound.wav
sound/gunmanchronicles/weapons/KnifeHolster.wav
sound/items/9mmclip1.wav
sprites/gunmanchronicles/ballspark.spr
sprites/gunmanchronicles/glow01.spr
sprites/gunmanchronicles/laserbeam.spr
sprites/gunmanchronicles/rustbitglow.spr
sprites/lgtning.spr
sprites/steam1.spr
sprites/zerogxplode.spr
